In [1]:
from datetime import datetime
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np
import ast

In [3]:
def compute_common_authors(features_df, doi1, doi2):
    return len(set(features_df.loc[doi1, 'authors']).intersection(features_df.loc[doi2, 'authors']))

def compute_date_difference(features_df, doi1, doi2):
    date_format = "%Y-%m-%d"
    d1 = datetime.strptime(features_df.loc[doi1, 'publication_date'], date_format)
    d2 = datetime.strptime(features_df.loc[doi2, 'publication_date'], date_format)
    return abs((d1-d2).days)

def create_input_vector(features_df, doi1, doi2):
    return (ast.literal_eval(features_df.loc[doi1, 'title_sbert_embeddings']) + ast.literal_eval(features_df.loc[doi2, 'title_sbert_embeddings']) +
            [compute_common_authors(features_df, doi1, doi2), compute_date_difference(features_df, doi1, doi2)])

def create_labels(features_df, links_df, doi1, doi2):
    type1 = features_df.loc[doi1, 'paper_type']
    type2 = features_df.loc[doi2, 'paper_type']
    return int(len(links_df[(links_df[f'{type1}_doi'] == doi1) &
                            (links_df[f'{type2}_doi'] == doi2)]) == 1)

# test create_labels
# print(create_labels(features_df, links_df, '10.5334/johd.1', '10.1080/03071022.2014.975943'))
# print(create_labels(features_df, links_df, '10.5334/johd.4', '10.5334/johd.1'))

In [5]:
# ,doi,title,paper_type,concepts,authors,publication_date,title_sbert_embeddings
features_df = pd.read_csv('../data/paper-features.csv', index_col='doi')
links_df = pd.read_csv('../data/links.csv')

In [10]:
print(links_df.shape)
print(len(set(links_df['data_paper_doi']).union(set(links_df['research_paper_doi']))))
links_df.head(2)

(80, 9)
152

,Unnamed: 0,data_paper_doi,research_paper_doi,data_paper_url,research_paper_url,research_paper_file_url,data_paper_has_file,research_paper_has_file,source
0,0,10.5334/johd.1,10.1080/03071022.2014.975943,https://openhumanitiesdata.metajnl.com/article...,https://www.tandfonline.com/doi/full/10.1080/0...,http://sro.sussex.ac.uk/id/eprint/51704/1/RSHI...,True,True,original-johd
1,1,10.5334/johd.1,10.1080/01615440.2015.1007194,https://openhumanitiesdata.metajnl.com/article...,https://www.tandfonline.com/doi/full/10.1080/0...,https://discovery.ucl.ac.uk/10105667/1/Irish%2...,True,True,original-johd

In [7]:
print(features_df.shape)
features_df.head(2)

(148, 7)

,Unnamed: 0,title,paper_type,concepts,authors,publication_date,title_sbert_embeddings
doi,,,,,,,
10.1002/asi.24499,0,Harmonizing and publishing heterogeneous premo...,research_paper,"['https://openalex.org/A5010723046', 'https://...","['https://openalex.org/A5010723046', 'https://...",2021-05-26,"[-0.3494153618812561, 0.05191454291343689, -0...."
10.1002/hipo.23539,1,Single neurons in the human medial temporal lo...,research_paper,"['https://openalex.org/A5034612103', 'https://...","['https://openalex.org/A5034612103', 'https://...",2023-04-15,"[0.35188332200050354, -0.49159741401672363, -0..."

In [11]:
# Splitting data into training and testing
# X_train, X_test, y_train, y_test = train_test_split(df, df['paper_type'], test_size=0.2, stratify=df['paper_type'])
all_data_orig = []
for doi1 in features_df.index:
    for doi2 in features_df.index:
        if doi1 == doi2:
            continue
        all_data_orig.append((create_input_vector(features_df, doi1, doi2), 
                            create_labels(features_df, links_df, doi1, doi2)))

In [12]:
all_data_xs = torch.tensor([a[0] for a in all_data_orig])
all_data_ys = torch.tensor([a[1] for a in all_data_orig], dtype=torch.float)
mean = all_data_xs.mean(dim=0)
std = all_data_xs.std(dim=0)
all_data_xs = (all_data_xs - mean) / std # normalize (convert to z-scores)

In [17]:
all_data_xs.shape # ~= 22k ~= 150*150

torch.Size([21756, 770])

In [13]:
all_data = pd.DataFrame({'x': [x for x in all_data_xs], 'y': all_data_ys})

In [14]:
print(all_data.shape)
print(all_data.iloc[0,:])
print(all_data.iloc[0,0])

(21756, 2)
x    [tensor(-0.8719), tensor(0.1038), tensor(-0.36...
y                                                  0.0
Name: 0, dtype: object
tensor([-8.7190e-01,  1.0382e-01, -3.6415e-01, -4.6531e-01,  2.1592e-01,
         3.5139e-01, -2.0454e+00,  8.8322e-01,  2.2723e-01, -7.3340e-01,
         2.7582e-01,  8.7743e-01, -3.2823e-01, -3.8814e-01,  2.1121e-02,
        -1.3024e-01,  1.6216e-01,  5.1751e-01, -1.2578e-01,  3.0445e-01,
        -1.0728e+00,  9.8676e-01,  2.3396e-02, -1.1142e+00, -1.2762e-01,
        -5.1336e-01, -9.8808e-01, -3.5440e-01,  1.2028e+00, -1.1432e+00,
         5.7619e-01,  2.2760e-01,  6.5965e-01,  3.2077e-01,  1.0211e-01,
        -7.8394e-01, -3.0697e-01,  2.2297e-01, -9.3478e-01, -3.3195e-01,
         1.0131e-01,  5.4721e-01, -1.5130e+00,  1.5290e+00, -2.8460e-01,
        -5.9774e-01, -7.9322e-01,  1.2300e-01, -2.0930e-01,  1.1203e+00,
        -5.3162e-01,  1.2684e-01, -1.6843e+00,  5.3717e-01,  8.6158e-01,
         4.6147e-01, -2.7514e-01, -4.2944e-01, -1.5444e-01, -6.0735e-02,
        -3.6290e-01,  1.0590e+00, -1.1173e+00, -5.1576e-01,  9.0735e-01,
         3.5822e-02,  1.5941e+00,  2.3410e-01,  6.3406e-01,  3.5226e-01,
        -9.7832e-02,  8.8818e-01,  2.1882e-01,  2.0999e+00,  1.2960e-02,
         1.4719e-01, -1.7122e+00,  1.1218e+00,  2.8691e-01, -1.1167e+00,
        -5.9187e-01,  2.2875e-01, -6.9762e-01, -1.7186e-01, -1.0515e+00,
        -2.6262e-01,  7.1775e-01,  1.8674e-01, -8.6347e-01,  4.2840e-01,
         6.9764e-01,  1.7149e-01,  4.6465e-02,  2.1753e-01,  1.4420e-02,
        -1.0165e-01, -2.0545e-01,  1.2074e+00,  1.1050e+00,  1.0299e+00,
        -1.0418e+00, -2.3464e-01, -1.6417e-01,  4.3172e-01, -9.8733e-01,
        -1.4836e+00,  1.5847e+00, -1.4370e+00, -9.5472e-01, -8.0642e-01,
        -1.8703e-01,  1.6565e-05, -2.1621e-01, -1.3136e+00,  3.1452e-01,
         1.4088e-01,  1.0020e+00,  7.2785e-01,  3.0508e-01, -4.4751e-02,
         2.4341e-01,  3.7905e-01, -5.7028e-02, -1.8523e-01,  1.7704e-02,
        -7.2888e-01,  2.9230e-03, -4.5676e-01, -1.3036e-01, -1.8012e+00,
         3.0097e-01,  8.7393e-01,  2.0911e+00,  1.6656e-01,  3.2678e-01,
        -9.8986e-01, -1.7397e+00, -6.6917e-01,  4.6214e-01,  5.6386e-01,
        -6.7456e-01, -2.3761e-01, -2.3554e-01,  1.0813e+00, -7.3808e-03,
         2.0623e+00,  8.2059e-01,  4.9263e-01,  1.0953e+00, -1.9613e-02,
         3.2327e-01,  2.9062e-01, -2.7147e-01,  4.8242e-02, -4.6482e-01,
        -1.0187e+00,  1.1442e+00,  4.8930e-01, -1.1692e+00, -1.0055e+00,
        -6.0552e-01, -8.0652e-01, -1.0317e+00,  4.6530e-01,  2.5953e-01,
        -1.2788e+00,  1.3297e+00,  6.3347e-01, -6.2514e-01,  1.7454e-01,
         1.0078e+00, -6.6742e-01, -6.1636e-01, -1.5971e-01, -3.2663e-01,
         5.2732e-01,  4.8111e-01, -9.1185e-01, -1.0693e+00, -8.3588e-01,
         4.0011e-01,  8.2241e-01,  4.6481e-02,  1.1809e+00, -6.0850e-01,
        -8.4510e-01, -9.8779e-01,  5.0595e-02,  1.3188e+00,  1.8874e+00,
        -8.0904e-01,  1.0812e-01,  2.2127e-01, -7.8741e-01, -1.7946e-01,
        -1.0764e+00,  2.4754e+00, -4.1318e-02, -5.1092e-01, -6.7350e-01,
         2.5785e-01,  2.2418e-01,  2.1614e-01,  1.2616e+00, -8.7786e-01,
         6.2707e-01,  1.3054e-01, -2.7276e-01, -2.9464e-01,  2.5318e-01,
        -9.6932e-01,  6.3743e-01, -9.5569e-01,  1.5711e+00, -7.2076e-01,
         8.2721e-01, -1.0548e+00,  1.1293e+00,  1.3181e+00, -4.4958e-02,
        -6.8827e-01, -4.8113e-01,  3.9075e-01, -3.0114e-01,  4.3818e-01,
         2.6400e-01, -7.4395e-01,  6.4762e-01, -1.5664e+00,  8.2699e-01,
        -1.0681e+00, -1.0954e+00, -1.1118e+00, -1.0477e+00,  2.0193e-01,
        -7.1294e-01,  1.4359e+00, -9.8789e-01, -7.0457e-01, -1.1875e-01,
        -3.7306e-02,  1.1626e+00,  2.8485e-01, -4.0479e-02, -3.1463e-01,
        -4.2647e-01,  1.1065e-02,  2.3416e+00,  1.7991e+00, -1.1217e+00,
        -6.1728e-01,  1.2572e+00,  9.0371e-01, -7.7440e-02,  7.7656e-02,
        -6.3831e-01,  6.6241e-01, -1.1163e+00, -4.0765e-01,  5.6852e-01,
         6.7049e-01, -9.8424e-01,  1.4283e+00,  1.4829e+00,  1.3671e+00,
         1.3263e+00, -1.3522e+00, -2.0710e+00,  4.8297e-01, -9.8307e-01,
        -7.9323e-01,  2.1891e-01,  7.6782e-01, -3.6580e-01, -2.5830e-01,
         1.1170e+00, -2.4480e-01, -1.6992e+00, -3.6724e-01,  1.0459e+00,
        -7.9616e-01, -4.3654e-01,  1.8798e-01,  4.5421e-01,  8.6673e-01,
         2.1122e-02,  1.1153e+00,  1.4872e-02, -1.8530e-01, -4.7974e-01,
         5.7568e-01, -1.0652e+00, -2.3352e-01, -3.0908e-01, -1.4305e-01,
        -7.7544e-01,  7.7253e-01, -9.6877e-01,  1.5017e+00, -3.3915e-01,
         2.2887e-01, -8.2739e-01, -1.3437e-01,  9.1434e-01, -1.0304e+00,
        -7.7459e-02, -7.4250e-01,  1.3956e+00,  2.5524e-01, -3.1127e-01,
         1.2962e+00,  3.8156e-01, -3.5460e-01, -4.0904e-01,  6.3571e-01,
        -1.1400e-01,  7.0346e-01,  9.1495e-01, -6.5082e-01,  4.2597e-01,
         6.6285e-02, -1.2302e+00,  6.2474e-01,  7.2545e-01,  7.9045e-01,
         8.8999e-01, -1.5264e-01, -2.6355e-01,  1.0660e+00,  1.0223e+00,
        -8.3011e-01, -1.3358e+00, -1.3553e+00, -3.4907e-01, -4.2242e-01,
         4.5871e-02,  2.6104e-01,  7.0627e-02, -8.4364e-02, -1.4412e+00,
         5.1722e-01,  8.1994e-01, -1.3513e+00, -8.9349e-01, -2.5017e-01,
         1.4151e-01, -5.4274e-02, -6.6201e-01,  4.6342e-01,  1.3098e+00,
        -5.2655e-01, -2.5135e-01,  4.1447e-01,  1.6349e-01, -5.4083e-01,
         2.9981e-01,  7.1596e-01,  5.7453e-01, -1.6508e+00, -1.3711e-02,
         6.1068e-01,  4.7148e-01, -1.9040e+00, -5.4488e-01,  9.8770e-01,
        -5.5741e-01, -1.1703e-01,  5.6302e-01,  6.3799e-01,  4.5058e-01,
         8.8358e-01, -1.0268e-02,  8.8065e-01,  1.0497e-01, -5.6480e-01,
         4.4721e-01, -2.6045e-01, -1.0164e-01,  1.0215e+00,  2.6360e-01,
         2.5270e-01, -1.3773e-01,  9.5565e-02,  6.6623e-01,  1.5978e+00,
        -1.7121e+00, -6.4610e-01,  3.6614e-01, -1.1669e+00,  4.5310e-01,
         8.4158e-01, -5.9755e-01,  1.6094e+00,  1.1401e-01,  5.5748e-01,
         4.8225e-01, -5.3826e-01,  1.5885e+00,  2.7652e-01, -9.9264e-01,
        -2.7159e-01,  1.3128e+00, -4.3171e-01,  6.3716e-01,  7.4659e-01,
        -1.2116e+00,  6.8242e-01, -6.3822e-02, -4.9186e-01,  1.6347e+00,
         9.9353e-01, -6.0048e-01,  1.3417e+00, -9.0749e-01, -3.2475e-01,
         1.6068e-01,  1.0238e+00, -1.0277e+00, -1.7632e+00,  1.5466e+00,
        -6.7091e-01,  1.2199e-01,  7.0131e-01, -2.4486e-01, -5.6938e-03,
         4.1004e-01,  5.1763e-01,  1.1677e+00,  4.1514e-01,  1.2507e+00,
        -6.8286e-02, -1.7429e-01, -9.5583e-01, -3.5305e-01, -9.5565e-02,
         4.9291e-03,  1.0852e+00,  9.1472e-01,  1.6045e-01,  1.9444e+00,
         1.0236e-01,  9.2266e-01,  1.1429e+00,  6.1052e-01, -3.3486e-01,
        -3.2115e-01, -5.1693e-02, -1.3022e+00, -7.6068e-01, -7.1106e-02,
        -2.3947e-01, -1.8961e+00, -2.0201e-01,  2.1750e-01, -6.1434e-01,
         5.0401e-01,  5.7600e-01, -1.0677e+00,  2.0240e+00, -1.8541e+00,
         6.2180e-01,  6.9053e-01,  5.2294e-01, -1.2178e+00,  5.0713e-01,
         7.4969e-01, -4.4705e-01,  4.3256e-01,  1.7892e+00,  1.2603e-01,
        -8.3161e-01, -1.1247e+00, -1.0534e+00, -6.3380e-01, -3.3983e-01,
        -6.3945e-02, -6.8239e-01, -1.6452e+00, -6.5490e-01, -1.4543e+00,
         1.5622e-02,  1.6497e+00, -8.6008e-01, -4.6640e-01, -4.2210e-01,
         9.8703e-01,  4.3463e-01,  1.2567e+00,  1.2112e+00, -6.2546e-01,
         1.3914e+00, -1.0068e+00, -1.6805e-01,  9.1098e-01, -1.8845e-01,
         9.0327e-02, -4.4808e-01,  9.6693e-01,  6.4711e-01, -1.1708e+00,
        -7.8281e-01, -1.9212e-01,  8.6358e-01,  5.0995e-02, -1.2450e+00,
        -6.1472e-01, -1.5193e+00,  6.0790e-01, -8.5888e-01, -8.0721e-01,
        -8.0474e-01, -7.8799e-01,  2.2018e-01, -7.6783e-01, -1.2198e+00,
         1.7657e-01, -1.3709e+00, -2.4760e-02, -7.7504e-01,  5.5648e-01,
         1.9574e+00, -1.5622e+00, -2.9312e-01, -6.3079e-01,  8.2762e-01,
         2.3072e+00, -7.6639e-01, -8.2160e-01, -8.0333e-01,  9.3667e-01,
         3.2517e-01, -4.1965e-01,  8.7743e-03,  1.1954e+00, -7.4720e-01,
        -1.1813e+00, -9.6352e-01, -1.7652e+00,  1.6751e-01, -2.5295e-01,
        -1.0594e+00,  5.1686e-01, -2.0927e+00,  1.2804e-01, -7.7678e-01,
        -1.7404e-02, -1.6402e+00,  5.8903e-01,  1.1660e+00,  8.1265e-01,
         1.4015e+00, -5.5676e-01, -1.5561e-01,  6.7468e-01,  9.0941e-02,
        -1.6867e+00, -1.7018e+00,  5.8697e-01,  8.4249e-01,  1.1510e+00,
        -1.3754e+00, -1.3416e+00, -6.8531e-01, -4.3265e-01,  4.5273e-01,
        -1.4212e+00, -6.4653e-01,  2.8078e-01,  5.8900e-01, -2.0515e-01,
         5.5896e-01,  9.9552e-01, -1.2888e+00,  3.4581e-01, -1.3159e-01,
         8.7138e-01, -1.9022e-01,  8.3673e-01, -7.8685e-01, -4.2365e-01,
         1.0011e+00, -2.3845e-01, -2.0627e-01,  2.2434e-01, -5.4067e-01,
        -8.8269e-01, -6.2880e-01,  1.6696e-01,  3.8744e-01, -1.0967e+00,
        -2.3125e+00,  1.2791e+00,  1.0469e+00, -1.1094e+00,  3.1870e-02,
        -6.8012e-01,  6.6315e-01,  9.2785e-01,  1.6272e+00, -1.7400e+00,
        -5.7699e-01,  2.6247e-01, -1.7273e-01, -5.8723e-01,  6.4951e-01,
         4.1101e-01, -1.5729e-02,  7.7654e-01, -1.2334e+00, -1.2550e-01,
        -8.7237e-02,  3.0423e-01,  1.5062e-01,  3.9159e-01,  2.4011e-01,
         9.3718e-02, -1.6136e+00, -8.5471e-01, -3.6013e-01,  4.0450e-01,
        -1.3624e+00, -2.6762e-01,  1.3774e-01, -8.6863e-01,  1.2686e-01,
        -8.9131e-01,  1.8582e-01,  1.6742e-01,  3.7320e-01, -6.0184e-01,
        -8.8745e-02,  1.4012e+00,  1.3295e+00,  1.2829e+00,  3.5720e-01,
         2.1884e+00, -4.3817e-01,  4.4559e-02, -4.5382e-01, -8.8966e-01,
         1.2666e-01, -7.1682e-02,  1.5257e+00, -8.5319e-01, -2.2458e+00,
        -3.7601e-02, -4.2729e-01,  1.5068e-01,  6.8502e-01,  8.8864e-01,
        -6.8890e-01,  9.5076e-01,  1.4685e+00,  1.2755e+00, -1.7950e-02,
         1.1249e-01, -1.7030e+00,  6.2418e-01, -3.4662e-01, -1.7745e-01,
        -2.8370e-01, -5.9020e-01, -1.0623e+00, -7.6001e-01, -6.1301e-01,
        -3.6255e-01,  2.1141e+00, -6.4866e-01, -6.6980e-02, -9.4537e-01,
         1.0139e-01,  3.7337e-01,  1.4866e+00,  7.8122e-01,  9.8407e-01,
         2.4576e-02,  1.4784e+00,  8.7090e-01, -1.4298e-01,  1.1244e+00,
         1.2535e-01, -1.2190e+00, -1.0865e-02,  2.1865e-01,  1.0922e+00,
        -3.8808e-01,  5.3642e-01, -2.3398e-02,  1.2451e-01,  3.8340e-01,
        -3.4622e-01, -6.2031e-01, -1.9989e+00,  1.2498e+00, -1.0241e+00,
         1.1934e+00, -9.0739e-01, -1.7652e-01,  1.8383e-01,  1.8275e+00,
         9.7643e-01,  1.7443e-01, -7.5683e-01, -5.8643e-01, -9.6546e-01,
        -8.1258e-01, -8.0280e-01, -2.8430e-01,  2.0613e-02, -2.3919e+00,
         7.8250e-01,  3.3522e-01, -1.2882e+00, -5.7599e-01, -4.0642e-01,
        -9.3044e-01,  1.4529e+00, -3.4105e-01,  1.6164e+00,  1.1865e+00,
         8.5859e-01,  4.7099e-01, -2.2943e-01,  2.0392e-01,  9.3271e-01,
        -1.5543e+00,  7.5440e-01,  1.0691e+00,  5.0202e-01, -5.3781e-02,
        -8.1530e-01,  2.1636e+00,  5.5472e-01, -1.0105e+00,  8.3080e-01,
        -2.4214e-01,  1.0971e+00,  1.0191e+00,  7.2038e-01, -1.2535e+00,
        -4.7534e-02, -4.1458e-01,  5.5034e-01,  7.9925e-01, -8.4580e-01,
        -1.6851e+00,  1.2124e+00,  7.4651e-01, -5.9621e-01, -3.2331e-01,
         1.3348e+00,  6.2386e-02,  1.2667e-01, -3.4791e-01, -7.1030e-01,
         2.2383e+00,  7.7872e-01,  1.4955e-01,  1.1427e+00,  1.9270e+00,
         4.4667e-01,  2.0905e-04, -1.3996e+00,  2.0074e-01,  6.1144e-01,
         2.0284e+00, -2.0878e+00, -5.7301e-01,  7.8242e-01, -3.3298e-03])

In [15]:
all_data_pos = all_data[all_data['y'] == 1]

# as negative samples are way more than positive samples, we sample 2x positive samples 
all_data_neg = all_data[all_data['y'] == 0].sample(2*len(all_data_pos))
all_data = pd.concat([all_data_pos, all_data_neg]).sample(frac=1.0)

In [18]:
train_data = all_data[0:2*len(all_data)//3]
test_data = all_data[2*len(all_data)//3:]
print(train_data.shape, test_data.shape)

(304, 2) (152, 2)

In [19]:
# Model Definition
class PaperRelationClassifier(nn.Module):
    def __init__(self):
        super(PaperRelationClassifier, self).__init__()
        self.fc1 = nn.Linear(770, 128)
        self.dropout1 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(128, 64)
        self.dropout2 = nn.Dropout(0.5)
        self.fc3 = nn.Linear(64, 1)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.dropout1(x)
        x = torch.relu(self.fc2(x))
        x = self.dropout2(x)
        x = self.fc3(x)
        x = torch.sigmoid(x)
        return x

In [20]:
# Model Training
from tqdm import tqdm

model = PaperRelationClassifier()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
num_epochs = 5

for epoch in tqdm(range(num_epochs)):
    for inputs, label in train_data.itertuples(index=False):
        optimizer.zero_grad()
        output = model(inputs)
        loss = criterion(output.squeeze(), torch.tensor(label))
        loss.backward()
        optimizer.step()

c:\Users\k21191796\Downloads\wr\nlp-automatic-linking\nlp-automatic-linking-proj\.conda\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 5/5 [00:03<00:00,  1.52it/s]

In [21]:
# Model Evaluation
model.eval()
all_preds = []
all_labels = []
with torch.no_grad():
    for inputs, label in test_data.itertuples(index=False):
        output = model(inputs)
        pred = (output.squeeze() > 0.5).float()
        all_preds.append(pred.numpy())
        all_labels.append(label)

accuracy = accuracy_score(all_labels, all_preds)
print(f'Accuracy: {accuracy * 100:.2f}%')
print('Classification Report:')
print(classification_report(all_labels, all_preds))

Accuracy: 62.50%
Classification Report:
              precision    recall  f1-score   support

         0.0       0.70      0.81      0.75       105
         1.0       0.33      0.21      0.26        47

    accuracy                           0.62       152
   macro avg       0.52      0.51      0.50       152
weighted avg       0.58      0.62      0.60       152